# Build the Kademlia cluster node components
# First generate protobuf definitions and then build the project
build-server: generate-protobuf src/server/*
	cd src/server && go build .

generate-protobuf: src/kademliapb/*.proto
	cd src && protoc -I kademliapb/ kademliapb/kademlia.proto --go_out=plugins=grpc:kademliapb

# Run all the server tests
server-test: build-server
	cd src/server && go test -v

build-docker-container: generate-protobuf
	docker build -t kademlia:local .

publish-to-docker-hub: build-docker-container
	docker login
	docker tag kademlia:local su225/kademlia:0
	docker push su225/kademlia:0

# Clean all the files generated by the build process
clean:
	rm -rf src/server/server
	rm -rf src/kademliapb/*.pb.go