# Build the Kademlia cluster node components
# First generate protobuf definitions and then build the project
build-server: src/server/*
	cd src && protoc -I kademliapb/ kademliapb/kademlia.proto --go_out=plugins=grpc:kademliapb && \
	cd server && go build .

# Run all the server tests
server-test: build-server
	cd src/server && go test -v

# Clean all the files generated by the build process
clean:
	rm -rf src/server/server
	rm -rf src/kademliapb/*.pb.go